### ISSUE TITLE
segementation fault when running fastSMC

### ISSUE THREAD

**Issue by malawsky** [PalamaraLab/FastSMC#1]
I am running fastSMC. I get the following errors:

Read 38939 samples.
Read data for 77878 haploid samples and 12500 markers, 0 of which are monomorphic. This job will focus on 77878 haploid samples.
Using precomputed decoding info from SAS_decode.csfs
Will decode using AVX instruction set.

Segmentation fault

I am unsure what to change. Thanks!

The command I am running is 

./fastsmc/build/FastSMC_exe --inFileRoot 17_phased --outFileRoot fastSMC_SAS_2 --decodingQuantFile SAS_decode.csfs

**Comment by brianzhang01** [comment]
A quick check is to make sure that all your file paths are correct.

**Comment by fcooper8472** [comment]
Hi @malawsky, I can't see anything immediately obvious that would be causing this.

Could you give some more information about your use case, e.g. what compiler options you are using? Would it be possible for you to share the data you're using so that I can try to reproduce the problem?
