### ISSUE TITLE
fastSMC running much slower than expected

### ISSUE THREAD

**Issue by malawsky** [PalamaraLab/FastSMC#2]
Hello,

I am using fastSMC and it seems to be running much slower than expected. I am running it on 30 nodes with 20 G allocated to the job. Below are the parameters:

Binary output ? false
Time threshold to define IBD in generations : 100
Use batches ? true
Batch size : 32
Running job 1 of 1
Recall level 3
skipCSFSdistance is 0
compress ? false
useAncestral ? false
outputIbdSegmentLength ? false
doPerPairPosteriorMean ? false
doPerPairMAP ? false
noConditionalAgeEstimates ? false
Use GERMLINE as a preprocessing step ? false
Read 38938 samples.
Read data for 77876 haploid samples and 21788 markers, 0 of which are monomorphic. This job will focus on 77876 haploid samples.

The decoding quant file looks to be a comparable size to the ones provided as an example.

It has been running for 12 hours and is still this stage: Decoding progress: 0%  (1/3032296750).

Any suggestions as to what is going on?

Best,
Daniel

**Comment by fcooper8472** [comment]
The fact that it's still on 1 does look very suspicious. But, again, very difficult to diagnose without more info about what exactly you're running. Is the data you're using something that could be shared?

**Comment by fcooper8472** [comment]
@malawsky some other thoughts:

1. You are currently running 3,032,296,750 pairs, and it's very possible that progress has got past the first one, but not yet to 1% when it would next update the printout. That is an unfeasibly large computation to be doing on a single machine.
2. You are running with a single job, so all of the work will be carried out on a single core. This is OK if you are parallelising it yourself, for instance across chromosomes, but this might not be what you intend.

You might want to be using GERMLINE (which is currently set to false).  This will **substantially** reduce the number of pairs in the main computation.

**Comment by malawsky** [comment]
@fcooper8472  Thank you for your help. I am indeed parallelizing across chromosomes, but it is unclear what option I would use to multithread the job, I don't see it in the documentation.

I will add the GERMLINE option.

I can share the data for a sample chromosome, how should I go about sending it to you?

**Comment by fcooper8472** [comment]
A quick summary of what we have discussed:
- the GERMLINE flag does preprocessing by hashing. This will be changed to be ON by default (and renamed "hashing" to avoid possible confusion).
- other issues were to do with data being provided in the wrong format - we will try to improve error handling to make it clearer if something is wrong with the files, rather than just getting an unhelpful segfault, or producing garbage output.
