### ISSUE TITLE
qrules.mk: recipe for target 'ABM_SA.o' failed

### ISSUE THREAD

**Issue by pramod21233** [PalamaraLab/FastSMC#8]
Hi,
I am trying to build an application using the QNX SDP 7.0, and got following error - 
cc: C:/qnx700//host/win64/x86_64/usr/lib/gcc/arm-unknown-nto-qnx7.0.0eabi/5.4.0/cc1plus caught signal 1
C:/qnx700//target/qnx7/usr/include/mk/qrules.mk:67: recipe for target 'ABM_SA.o' failed
make[2]: *** [ABM_SA.o] Error 1
make[2]: Leaving directory 'C:/WRE_SW/BRAKING/FastBrake/AB_Manager/Source/ABM_Zynq/ABM_SA/arm/o-le-v7'
recurse.mk:96: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory 'C:/WRE_SW/BRAKING/FastBrake/AB_Manager/Source/ABM_Zynq/ABM_SA/arm'
recurse.mk:96: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by fcooper8472** [comment]
Closing as unrelated to this software.
